# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 000293e6f6bc3c634e67f44aef42323f0f8a79f75d666261cd2c945e2489fe571a9a10e0a8150a1fda4b57bab7be8d6499695aa65a9a07a79f48b6680102d7a6

test:
  secret_key_base: 2b3c7a77f6f365ede39e13f31d6e5f6a5e1ec17d9c0c7577e61f271bfc38f36667a9498a107c952f191267dc8f3bccafe90158a43b6ff8e46ad81955a2c370e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
